version: "2"
services:
  app:
    container_name: m4g247_app
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    # image: toantd14/mail4good-ts247:latest
    # image: freecodecamp/mail-for-good:stable
    env_file: ./app/.env
    links:
      - redis
      - postgres
    # restart: always
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    networks:
      - m4g247-network

  postgres:
    container_name: m4g247_postgres
    image: postgres:9.6.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_123
    networks:
      - m4g247-network

  redis:
    container_name: m4g247_redis
    image: redis:4.0
    restart: always
    ports:
      - 6379:6379
    networks:
      - m4g247-network

networks:
  m4g247-network:
    driver: bridge