version: "2"
services:
  app:
    image: freecodecamp/mail-for-good:latest
    # image: mail-for-good:1.2
    env_file: .env
    environment:
      - PSQL_USERNAME=postgres
      - PSQL_DATABASE=postgres
      - PSQL_HOST=postgres
      - REDIS_HOST=redis
      - VIRTUAL_HOST=app
      - VIRTUAL_PORT=8080
    container_name: m4g247_app
    links:
      - redis
      - postgres
    ports:
      - "80:8080"
  postgres:
    image: postgres:9.6.3
    container_name: m4g247_postgres
    ports:
      - 5432:5432
  redis:
    image: redis:4.0
    container_name: m4g247_redis
    ports:
      - 6379:6379